// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.20.0

package domain

import (
	"time"
)

type Account struct {
	ID        int64
	Owner     string
	Balance   int32
	Currency  string
	CreatedAt time.Time
	UpdatedAt time.Time
}

type Entry struct {
	ID        int64
	AccountID int64
	Amount    int32
}

type Transfer struct {
	ID            int64
	FromAccountID int64
	ToAccountID   int64
	Amount        int32
	CreatedAt     time.Time
	UpdatedAt     time.Time
}
